# Generated by Django 5.1.1 on 2024-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='año_compra',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
